### ISSUE TITLE
Add support for twig views

### ISSUE THREAD

**Issue by raizdev** [Doc077/melonly#1]
Maybe (just an idea) because there are users like i am who not using react to add support for using twig.
You create a variable in .env called "VIEW=twig/react" whatever that call the function in View.php to call the render function

**Comment by Doc077** [comment]
Hi there,
Thank you for this suggestion. I'll try to add this feature in the 7.0.0 release (maybe with optional React installation so there wouldn't be it at all if you don't use it). I will also improve built-in view template engine. I hope that will make Melonly a better framework :)

**Comment by raizdev** [comment]
Sounds good! I'm planning when twig is added to use this framework for my project
